### ISSUE TITLE
send cookie失败

### ISSUE THREAD

**Issue by Hyingerrr** [fangyuan99/cookie-share#1]
生成了随机的id，填写了server url之后，我能访问/admin后台，点击send cookie时报错Error sending cookies，怎么查看是哪里问题呢？

**Comment by fangyuan99** [comment]
![image](https://github.com/user-attachments/assets/e89b6149-04af-49d1-8272-a734f68f8458)
你可以试试这个，看看报错信息

**Comment by fangyuan99** [comment]
![image](https://github.com/user-attachments/assets/7b67286c-ee36-410a-8dd0-7b00061dc930)
或者在worker里面打开日志试试

**Comment by fangyuan99** [comment]
还有就是你的URL后面是否带了`/`，如果带了去掉试试
