### ISSUE TITLE
DZ论坛源码做的网站使用插件同步账号失败。

### ISSUE THREAD

**Issue by Xion2023** [fangyuan99/cookie-share#2]
Receive后，账号并未登录，其他网站测试正常

**Comment by Xion2023** [comment]
使用Cookie-Editor插件正常导入是可以登录的！

**Comment by fangyuan99** [comment]
暂时没排查出问题，等有空再研究一下

**Comment by fangyuan99** [comment]
新版已修复 https://github.com/fangyuan99/cookie-share/releases/latest
