### ISSUE TITLE
希望支持firefox

### ISSUE THREAD

**Issue by sinnerliu** [fangyuan99/cookie-share#3]
双浏览器使用者，希望支持firefox浏览器，感谢大佬

**Comment by fangyuan99** [comment]
暂时可以用 https://chromewebstore.google.com/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm 插件替代
我后面有空研究一下

**Comment by fangyuan99** [comment]
已更新，如有问题可以及时反馈
https://github.com/fangyuan99/cookie-share/blob/firefox/README_CN.md#%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
https://github.com/fangyuan99/cookie-share/releases/download/v0.1.4/cookie-share-firefox_v0.1.4.xpi

**Comment by sinnerliu** [comment]
![image](https://github.com/user-attachments/assets/47f184e0-1518-469c-9973-2a3656226b46)
火狐上面接收有问题
