### ISSUE TITLE
无需输入密码，可以直接查看到cookie数据

### ISSUE THREAD

**Issue by Xion2023** [fangyuan99/cookie-share#4]
使用，https://your-worker-name.your-subdomain.workers.dev/admin/list-cookies  可以直接查看到cookie列表，感觉有安全隐患！

**Comment by fangyuan99** [comment]
确实，改代码的时候不小心把这一段删去了，现在紧急修复

**Comment by fangyuan99** [comment]
已修复，紧急更新
